name: Python Email Quote Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Check Python version
        run: python --version

      - name: Check files
        run: |
          ls
          python -m py_compile main.py

      - name: Success
        run: echo "Workflow is working"
